/**
 * The mimir side of the `/plans` board — one record per plan file in the wiki's
 * `plans/` directory, plus the hand-ordered `plans/queue.yaml`.
 *
 * Three things about the shape are deliberate:
 *
 *   1. **The root comes from the wiki registry, never from a hard-coded path.**
 *      mimir is registered through `WIKI_EXTRA` (`mimir=../mimir` on this host),
 *      so `findWiki(getWikiRegistry(), "mimir")` is the one place that knows
 *      where it lives. A second literal path here would be a fourth source of
 *      truth that goes wrong on the other machine.
 *   2. **Every record carries the file's sha256.** `writeWikiPage` takes a
 *      `baseHash` and answers `stale` when it does not match
 *      (`src/wiki/page-write.ts`), so a board that renders a card without
 *      carrying its hash forward degrades the later compare-and-swap into a
 *      no-op check. The hash is part of the read, not decoration.
 *   3. **The frontmatter parse is FENCE-SCOPED, never a line grep.**
 *      `plans/mimir-plan-status-lifecycle.mdx` carries `plan_status:` at line 5
 *      AND inside a fenced YAML example around line 145; a grep reads that file
 *      as having two statuses. `parseFrontmatter` (wiki/store.ts) slices the
 *      leading `---`…`---` block and nothing else, which is exactly the rule —
 *      it also already handles the two shapes plans use, `tags: [a, b]` flow
 *      arrays and quoted `status_note`, so this module reuses it rather than
 *      standing up a second frontmatter dialect.
 *
 * Read-only. Nothing here writes; PR 4 owns the write path.
 */

import path from "node:path";
import { readdir, stat } from "node:fs/promises";
import { getLog } from "../logging.ts";
import { parseFrontmatter } from "../wiki/store.ts";
import { sha256 } from "../gardener/util.ts";
import { getWikiRegistry } from "../wiki/registry-memo.ts";
import { findWiki } from "../wiki/registry.ts";
import { parseQueueYaml, type QueueOrder } from "./queue.ts";

const log = getLog("plans", "source");

/** The wiki this board reads. A name, not a path — see rule 1 above. */
export const PLANS_WIKI_NAME = "mimir";
/** Directory inside that wiki holding the plan pages. */
export const PLANS_DIR = "plans";
/** The queue file, relative to the wiki root. PR 4's writer targets this path. */
export const QUEUE_REL_PATH = `${PLANS_DIR}/queue.yaml`;

/** `plan_status` lifecycle values (mimir's contract, see
 *  `plans/mimir-plan-status-lifecycle.mdx`). Anything else is dropped. */
export const PLAN_STATUSES = [
  "proposed",
  "ready",
  "in-flight",
  "blocked",
  "shipped",
  "superseded",
  "abandoned",
] as const;
export type PlanStatus = (typeof PLAN_STATUSES)[number];

export const PLAN_PRIORITIES = ["p0", "p1", "p2", "p3"] as const;
export type PlanPriority = (typeof PLAN_PRIORITIES)[number];

/** Files in `plans/` that are not plans. `index.md` is generated by mimir's
 *  `build-plans-index.ts`; everything else is filtered by the real test — a
 *  plan is a file whose FRONTMATTER carries `plan_status`. */
const NON_PLAN_BASENAMES = new Set(["index.md", "index.mdx"]);

const STATUS_DATE_RE = /^\d{4}-\d{2}-\d{2}$/;

export interface PlanRecord {
  /** Filename without extension — the join key against the ledger and the
   *  identity `queue.yaml` ranks by. */
  slug: string;
  title: string;
  /** Undefined when the file carries a `plan_status` the enum does not know:
   *  the file is still a plan (it opted in), its state is just unknown. */
  planStatus: PlanStatus | undefined;
  /** `YYYY-MM-DD`, or undefined. **8 active plans carry none**, so no sort may
   *  assume it — {@link PlanRecord.mtimeMs} is the tie-breaker. */
  statusDate: string | undefined;
  statusNote: string | undefined;
  /** True only for the literal `followups: open`. */
  followupsOpen: boolean;
  priority: PlanPriority | undefined;
  tags: string[];
  /** Relative to the wiki ROOT (e.g. `plans/foo.mdx`) — the shape
   *  `writeWikiPage` takes. */
  relPath: string;
  /** File mtime, epoch ms. Age fallback for plans with no `status_date`. */
  mtimeMs: number;
  /** sha256 of the file's bytes — the `baseHash` a later write must present. */
  hash: string;
}

export interface PlanQueue {
  order: QueueOrder;
  /** sha256 of `queue.yaml`'s bytes, or `""` when the file does not exist.
   *  The empty string is the BOOTSTRAP SENTINEL: PR 4's order endpoint accepts
   *  it only for an absent file, which is how the very first drag has a base to
   *  send. (Note it cannot be handed to `writeWikiPage`, whose CAS rejects a
   *  falsy `baseHash` outright — the order writer needs its own branch.) */
  hash: string;
}

export interface PlanSourceResult {
  /** Absolute wiki root, or null when mimir is not registered on this host. */
  root: string | null;
  plans: PlanRecord[];
  queue: PlanQueue;
  /** Everything dropped, in words. Also logged, aggregated, once per load. */
  warnings: string[];
}

export interface PlanSourceOptions {
  /** Absolute wiki root override — tests point this at a mkdtemp dir so they
   *  never depend on the real mimir checkout. Defaults to the registry entry. */
  root?: string;
}

function firstString(v: string | string[] | undefined): string | undefined {
  if (typeof v === "string") return v.trim() || undefined;
  if (Array.isArray(v)) return v[0]?.trim() || undefined;
  return undefined;
}

function asList(v: string | string[] | undefined): string[] {
  if (Array.isArray(v)) return v.map((s) => s.trim()).filter(Boolean);
  const one = firstString(v);
  return one ? [one] : [];
}

/** Build one record from a plan file's bytes. Exported so the parse is testable
 *  against a fixture without touching a filesystem at all. */
export function planRecordFromContent(
  relPath: string,
  content: string,
  mtimeMs: number,
  warnings: string[],
): PlanRecord | null {
  const fm = parseFrontmatter(content);
  const rawStatus = firstString(fm.plan_status);
  // The membership test: a plan is a file that OPTED IN by carrying the key.
  // Non-plan markdown that wanders into `plans/` is simply not a card.
  if (!rawStatus) return null;

  const slug = path.basename(relPath).replace(/\.mdx?$/i, "");

  let planStatus: PlanStatus | undefined;
  if ((PLAN_STATUSES as readonly string[]).includes(rawStatus)) {
    planStatus = rawStatus as PlanStatus;
  } else {
    warnings.push(`${relPath}: plan_status "${rawStatus}" is not in the enum — dropped`);
  }

  const rawPriority = firstString(fm.priority);
  let priority: PlanPriority | undefined;
  if (rawPriority) {
    if ((PLAN_PRIORITIES as readonly string[]).includes(rawPriority)) {
      priority = rawPriority as PlanPriority;
    } else {
      warnings.push(`${relPath}: priority "${rawPriority}" is not in the enum — dropped`);
    }
  }

  const rawDate = firstString(fm.status_date);
  let statusDate: string | undefined;
  if (rawDate) {
    // Presence is not enough: a `2026-7-3` sorts wrong against every other row,
    // and the board sorts on this field. Shape-check or drop.
    if (STATUS_DATE_RE.test(rawDate)) statusDate = rawDate;
    else warnings.push(`${relPath}: status_date "${rawDate}" is not YYYY-MM-DD — dropped`);
  }

  return {
    slug,
    title: firstString(fm.title) ?? slug,
    planStatus,
    statusDate,
    statusNote: firstString(fm.status_note),
    followupsOpen: firstString(fm.followups) === "open",
    priority,
    tags: asList(fm.tags),
    relPath,
    mtimeMs,
    hash: sha256(content),
  };
}

/** The mimir wiki root as the registry knows it, or null when unregistered. */
export function resolvePlansRoot(): string | null {
  return findWiki(getWikiRegistry(), PLANS_WIKI_NAME)?.root ?? null;
}

/**
 * Read every plan in the wiki's `plans/` directory plus `queue.yaml`.
 *
 * Never throws for corpus-level problems — an unregistered wiki, a missing
 * `plans/` directory, an unreadable file and an off-grammar queue all land in
 * `warnings` on an otherwise valid result, because the board must render the
 * cards it CAN read rather than 500 on one bad file.
 */
export async function loadPlanSource(opts: PlanSourceOptions = {}): Promise<PlanSourceResult> {
  const warnings: string[] = [];
  const root = opts.root ?? resolvePlansRoot();
  const empty: PlanQueue = { order: {}, hash: "" };
  if (!root) {
    warnings.push(
      `wiki "${PLANS_WIKI_NAME}" is not registered — set WIKI_EXTRA=${PLANS_WIKI_NAME}=<path>`,
    );
    return { root: null, plans: [], queue: empty, warnings };
  }

  const plansDir = path.join(root, PLANS_DIR);
  let entries: string[];
  try {
    entries = await readdir(plansDir);
  } catch (err) {
    warnings.push(`${PLANS_DIR}/ is unreadable: ${err instanceof Error ? err.message : String(err)}`);
    return { root, plans: [], queue: empty, warnings };
  }

  const plans: PlanRecord[] = [];
  for (const name of entries.sort()) {
    if (!/\.mdx?$/i.test(name)) continue;
    if (NON_PLAN_BASENAMES.has(name.toLowerCase())) continue;
    const abs = path.join(plansDir, name);
    let content: string;
    let mtimeMs: number;
    try {
      content = await Bun.file(abs).text();
      mtimeMs = (await stat(abs)).mtimeMs;
    } catch (err) {
      warnings.push(`${PLANS_DIR}/${name}: unreadable (${err instanceof Error ? err.message : String(err)})`);
      continue;
    }
    const record = planRecordFromContent(`${PLANS_DIR}/${name}`, content, mtimeMs, warnings);
    if (record) plans.push(record);
  }

  // The queue is validated against the slugs we just read, so an entry left
  // behind by a rename is dropped rather than ranking a card that is not there.
  const queueAbs = path.join(root, QUEUE_REL_PATH);
  let queue: PlanQueue = empty;
  const queueFile = Bun.file(queueAbs);
  if (await queueFile.exists()) {
    try {
      const text = await queueFile.text();
      const parsed = parseQueueYaml(text, new Set(plans.map((p) => p.slug)));
      warnings.push(...parsed.warnings);
      queue = { order: parsed.order, hash: sha256(text) };
    } catch (err) {
      warnings.push(`${QUEUE_REL_PATH}: unreadable (${err instanceof Error ? err.message : String(err)})`);
    }
  }

  // ONE aggregated warn per load. mimir's plans are re-read on every board
  // render; a corpus-wide backfill mistake would otherwise emit ~200 warns a
  // poll, which is how a real signal gets trained away.
  if (warnings.length > 0) {
    log.warn("plan source: {count} issue(s) reading {dir} — first: {first}", {
      count: warnings.length,
      dir: plansDir,
      first: warnings[0],
    });
  }

  return { root, plans, queue, warnings };
}
